
# Magstim command codes

SET_POWER_A = 0x40

SET_BASE_MODE = 0x45
ENABLE_REMOTE_CTRL = 0x51
DISABLE_REMOTE_CTRL = 0x52

GET_PARAMS = 0x4A


# BiStim-specific commands

SET_POWER_B = 0x41
SET_PULSE_INTERVAL = 0x43

ENABLE_HIRES_TIME = 0x59
DISABLE_HIRES_TIME = 0x5A


# Rapid-specific commands

SET_PULSE_FREQ = 0x42
SET_PULSE_COUNT = 0x44

IGNORE_COIL_INTERLOCK = 0x62
SET_RAPID_DURATION = 0x5B
ENABLE_ENHANCED_POWER = 0x5E
DISABLE_ENHANCED_POWER = 0x5F

GET_VERSION = 0x4E
GET_RAPID_PARAMS = 0x5C
GET_ERR_CODE = 0x49
GET_RAPID_STATUS = 0x78


# Instrument status bits

STATUS_STANDBY = 0
STATUS_ARMED = 1
STATUS_READY = 2
STATUS_COIL_PRESENT = 3
STATUS_REPLACE_COIL = 4
STATUS_ERR = 5
STATUS_ERR_TYPE = 6
STATUS_REMOTE_CTRL = 7


# Rapid status bits

RAPID_ENHANCED_POWER = 0
RAPID_TRAIN_STATUS = 1
RAPID_WAIT_STATUS = 2
RAPID_SINGLE_PULSE = 3
RAPID_HV_PSU = 4
RAPID_COIL_READY = 5
RAPID_THETA_PSU_CONFIG = 6
RAPID_COIL_ALGORITHM_MOD = 7


# Extended instrument status bits (Rapid-only)

STATUS_EXT_PLUS1_MODULE = 0
STATUS_EXT_SPECIAL_TRIGGER = 1


# Mode settings bits

MODE_STOPPED = 0
MODE_ARMED = 1
MODE_TRIGGER = 3
MODE_BASE = 6


# Additional command constants

PAD_BYTE = 0x40

INVALID_CMD = ord('?')
INVALID_DATA = ord('?')
SETTINGS_CONFLICT = ord('S')


# Magneto constants not from Magstim docs

CRC_ERROR = -1
